apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atms
resources:
  - 00-default-deny.yaml
  - 10-allow-dns.yaml
  - 20-allow-kafka.yaml
  - 30-allow-otel-collector.yaml
  - 40-allow-decision-engine.yaml
  - 41-allow-traffic-controller.yaml
